# Generated by Django 5.0 on 2024-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
