# Generated by Django 5.0.6 on 2024-07-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
